### PR TITLE
feature/homepage

### PR DESCRIPTION
**Pull request by Neelima1415**

### CODE REVIEW

**Review by swayampakula — APPROVED** [review]
Can you please make changes only for the projects done by you ? I can see the sound board project is done by Dathalakshmi and the index file changes are raised by Neelima for the same. Please have only your file changes.

**Review by swayampakula — CHANGES_REQUESTED** [review]
Can you please make changes only for the projects done by you ? I can see the sound board project is done by Dathalakshmi and the index file changes are raised by Neelima for the same. Please have only your file changes.

**Review by swayampakula — APPROVED** [review]
Looks fine

**Review by DathuKasturi834 — APPROVED** [review]
Looks fine

**Pull request merged**
