### PR TITLE
fix: added projects 

### PR DESCRIPTION
**Pull request by Neelima1415**
clear

### CODE REVIEW

**Review by swayampakula — CHANGES_REQUESTED** [review]
Wrongly done. This is not the expectation. 
Create a branch from the current merged main branch. View button should not take to the github but instead open the index.html of each project.

**Review by swayampakula — CHANGES_REQUESTED** [review]
I don't see the usage of HomePage Folder here. Hence remove the folder and commit back.

**Review by swayampakula — APPROVED** [review]
Looks fine

**Review by DathuKasturi834 — APPROVED** [review]
Looks fine

**Pull request merged**
